### ISSUE TITLE
Manage the merkle proof against the `selectedGER` in the PP

### ISSUE THREAD

**Issue by hadjiszs** [agglayer/agglayer#196]
For each `imported_bridge_exit` we want one inclusion proof `imported_bridge_exit -> selectedGER`

This inclusion proof has to be requested to the bridge service of the network `imported_bridge_service.sending_network`

**Comment by bpfarmer** [comment]
I'm not sure that this is the best approach. To see why, consider a chain that produces blocks with corresponding LERs `L_1, L_2, L_3, ..., L_n` during some period. At the end of the period, `L_n` is used in the construction of a GER.

Ideally, we'd like for a chain to be able to safely claim messages from `L_1` as soon as `L_1` is produced, without waiting for `L_n` and the construction of a GER. This is a precondition for fast interop. We would also like to generate the PP incrementally, after every few blocks, rather than once per epoch, as high-usage chains may have a ton of claims during an epoch.

The main change to enable this is to allow block/batch headers to take LERs instead of GERs for claims (and for these batch headers to be used in the execution and consensus proofs). From this perspective, I think that it could be nice in the PP to continue to take LERs instead of a GER, and then prove inclusion of those LERs in a GER during an aggregation step, because it allows us to easily check that the LERs that a chain includes as public inputs in the execution and consensus proofs are consistent with the public inputs in the pessimistic proofs. 

The counterargument is that the PP isn't required for fast interop, because we can generate the PP at the end of an epoch before settlement to L1. 

However, I still think that it would be annoying to need to update all claims to include a path to the GER rather than the LER. And the approach where we use LERs is more consistent with the final solution that we're trying to build, which is incremental proof generation for the PP, rather than a single pessimistic proof that spans an entire epoch. 

One intermediate step would be to still accept LERs for ImportedBridgeExits but prove inclusion of the LER into the GER within a single proof (no aggregation). To me, this would be preferable because it's more consistent with the eventual API, but curious what others think.
